CREATE TABLE AGENCIAS (
    agencia_id SERIAL,
    nombre VARCHAR2(50),
    pais VARCHAR2(50),
    fecha_fundacion TIMESTAMP,
    autor_examen VARCHAR2(150),
    CONSTRAINT PK_AGENCIA_ID PRIMARY KEY (agencia_id),
    CONSTRAINT NN_AGENCIA_NOMBRE (nombre IS NOT NULL),
    CONSTRAINT NN_AGENCIA_PAIS (pais IS NOT NULL),
    CONSTRAINT NN_AGENCIA_FECHA_FUNDACION (fecha_fundacion IS NOT NULL),
    CONSTRAINT NN_AGENCIA_AUTOR_EXAMEN (autor_examen IS NOT NULL)
);

CREATE TABLE SATELITES (
    satelite_id SERIAL,
    nombre VARCHAR2(50),
    orbita VARCHAR2(50),
    peso INT,
    coste DECIMAL(10, 2),
    activo BOOLEAN DEFAULT FALSE,
    fecha_lanzamiento TIMESTAMP,
    agencia_id INT,
    autor_examen VARCHAR2(150),
    CONSTRAINT PK_SATELITES_ID PRIMARY KEY (pk_id),
    CONSTRAINT FK_SATELITES_AGENCIAS_ID FOREIGN KEY (agencia_id) REFERENCES AGENCIAS (agencia_id),
    CONSTRAINT NN_SATELITES_NOMBRE (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITES_ORBITA (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITES_PESO (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITES_COSTE (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITES_ACTIVO (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITES_FECHA_LANZAMIENTO (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITES_AGENCIA_ID (nombre IS NOT NULL),
    CONSTRAINT NN_SATELITES_AUTOR_EXAMEN (nombre IS NOT NULL)
);

CREATE TABLE DETALLE_SATELITE (
    detalle_satelite_id SERIAL,
    velocidad_maxima INT,
    combustible INT,
    dias_vida_util INT,
    temperatura_maxima INT,
    satelite_id INT,
    autor_examen VARCHAR2(150),
    CONSTRAINT PK_DETALLE_SATELITE_ID PRIMARY KEY (detalle_satelite_id),
    CONSTRAINT FK_DETALLE_SATELITE_SATELITE_ID FOREIGN KEY (satelite_id) REFERENCES SATELITES (satelite_id),
    CONSTRAINT NN_DETALLE_SATELITE_VELOCIDAD_MEXIMA ( IS NOT NULL),
    CONSTRAINT NN_DETALLE_SATELITE_COMBUSTIBLE ( IS NOT NULL),
    CONSTRAINT NN_DETALLE_SATELITE_DIAS_VIDA_UTIL ( IS NOT NULL),
    CONSTRAINT NN_DETALLE_SATELITE_TEMPERATURA_MAXIMA ( IS NOT NULL),
    CONSTRAINT NN_DETALLE_SATELITE_SATELITE_ID ( IS NOT NULL),
    CONSTRAINT NN_DETALLE_SATELITES_AUTOR_EXAMEN ( IS NOT NULL),
    CONSTRAINT UQ_DETALLE_SATELITE_SATELITE_ID UNIQUE (satelite_id)
);